DROP TABLE  EDU  CASCADE CONSTRAINTS;
DROP TABLE  PET CASCADE CONSTRAINTS ;
DROP TABLE  MEMBER CASCADE CONSTRAINTS;
DROP TABLE  MESSAGE  CASCADE CONSTRAINTS;
DROP TABLE  PAYMENT  CASCADE CONSTRAINTS;
DROP TABLE  PREBOOKING  CASCADE CONSTRAINTS;
DROP TABLE  PREANSWER CASCADE CONSTRAINTS ;
DROP TABLE  QUESTION  CASCADE CONSTRAINTS;
DROP TABLE  ANSWER  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD  CASCADE CONSTRAINTS;
DROP TABLE  TIPBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  FREEBOARD CASCADE CONSTRAINTS ;
DROP TABLE  FREEBOARD_REPLY  CASCADE CONSTRAINTS;
DROP TABLE  MANAGER CASCADE CONSTRAINTS ;
DROP TABLE  FAQ CASCADE CONSTRAINTS ;
DROP TABLE  REPORT CASCADE CONSTRAINTS ;
DROP TABLE  NOTICE CASCADE CONSTRAINTS ;
DROP TABLE  BOOKING CASCADE CONSTRAINTS ;
DROP TABLE  REVIEW CASCADE CONSTRAINTS ;
DROP TABLE SITTERIMG CASCADE CONSTRAINTS ;
DROP TABLE COUNTVISITOR CASCADE CONSTRAINTS;

CREATE TABLE  EDU  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EDU_YN    VARCHAR2(100)      NOT NULL,
    SITTER_YN    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PET  (
    PET_NO    NUMBER      NOT NULL,
    PET_NAME    VARCHAR2(100)      NOT NULL,
    PET_BREADS    VARCHAR2(100),
    PET_DATE    DATE      NOT NULL,
    PET_SIZE    VARCHAR2(100)      NOT NULL,
    PET_GENDER    VARCHAR2(100)      NOT NULL,
    PET_NEUTRALIZE    VARCHAR2(100)      NOT NULL,
    PET_CHARATER    VARCHAR2(100)      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    PET_ORIGINFILE VARCHAR2(50),
    PET_REFILE VARCHAR2(50)
);
drop sequence seq_petno;
create sequence seq_petno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MEMBER  (
    USER_ID    VARCHAR2(100)      NOT NULL,
    EMAIL    VARCHAR2(100)      NULL,
    USER_NAME    VARCHAR2(100)      NULL,
    ADDRESS    VARCHAR2(100)      NULL,
    PHONE    VARCHAR2(100)      NULL,
    JOB    VARCHAR2(100)      NULL,
    PETSITTER    VARCHAR2(100)   default 'n'   NULL,
    PRICE    NUMBER      NULL,
    USER_DATE    DATE      NULL,
    PASSWORD    VARCHAR2(100)      NULL,
    USER_DELETE    VARCHAR2(100)  default 'n'   NULL,
    USER_ORIGINFILE VARCHAR2(100) NULL,
    USER_REFILE VARCHAR2(100) NULL,
    naver_code VARCHAR2(100) NULL,
    TITLE_IMG VARCHAR2(100) null,
    REPORT_ADD NUMBER default 0,
    PETSITTER_CONTENT VARCHAR2(3000) NULL
);

CREATE TABLE SITTERIMG (
	IMG_NO	VARCHAR2(100)		NOT NULL,
	USER_ID	VARCHAR2(100)		NOT NULL,
	IMG_ORIGINFILE	VARCHAR2(100)		NULL,
	IMG_REFILE	VARCHAR2(100)		NULL
);

drop sequence seq_IMGNO;
create sequence seq_IMGNO
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MESSAGE  (
    SENDER_ID    VARCHAR2(100)      NOT NULL,
    MESSAGE_TITLE    VARCHAR2(100)      NULL,
    MESSAGE_CONTENT    VARCHAR2(2000)      NULL,
    MESSAGE_READ    VARCHAR2(100)      NULL,
    MESSAGE_DATE    DATE  default sysdate    NULL,
    REICEIVER_ID    VARCHAR2(100)      NOT NULL
);

CREATE TABLE  PAYMENT  (
    BOOKING_NO    NUMBER      NOT NULL,
    PAYMENT_DATE    DATE      NOT NULL,
    PAYMENT_METHOD    VARCHAR2(100)      NOT NULL,
    PAYMENT_YN    VARCHAR2(100)      NOT NULL
);


CREATE TABLE  PREBOOKING  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    PREBOOKING_TITLE    VARCHAR2(100)      NOT NULL,
    PREBOOKING_CONTENT    VARCHAR2(100)      NOT NULL,
    PREBOOKING_DATE    DATE   default sysdate   NOT NULL,
    ANSWER_YN    VARCHAR2(100)      NOT NULL
);
drop sequence seq_prebookingno;
create sequence seq_prebookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  PREANSWER  (
    PREBOOKING_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    ANSWER_CONTENT    VARCHAR2(4000)      NOT NULL,
    ANSWER_DATE    DATE  default sysdate    NOT NULL
);

CREATE TABLE  QUESTION  (
    QUESTION_NO    NUMBER      NOT NULL,
    QUESTION_TITLE    VARCHAR2(100)      NOT NULL,
    QUESTION_CONTENT    VARCHAR2(4000)      NOT NULL,
    QUESTION_DATE    DATE  default sysdate    NOT NULL,
    REPLY_YN    VARCHAR2(100)      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    QUESTION_ORIGINAL_FILENAME VARCHAR2(100) null,
    QUESTION_RENAME_FILENAME VARCHAR2(100) null,
    QUESTION_REF number not null,
    QUESTION_REPLY_REF number not null,
    QUESTION_REPLY_LEV number not null,
    QUESTION_REPLY_SEQ number not null
);

drop sequence seq_QUESTIONno;
create sequence seq_QUESTIONno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  ANSWER  (
    QUESTION_NO    NUMBER      NOT NULL,
    REPLY_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPLY_DATE    DATE   default sysdate   NOT NULL
);

CREATE TABLE  TIPBOARD  (
    TIPBOARD_NO    NUMBER      NOT NULL,
    TIPBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    TIPBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    TIPBOARD_DATE    DATE  default sysdate    NOT NULL,
    TIPBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    TIPBOARD_VIEWS    NUMBER      NOT NULL,
    TIPBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPBOARD_DELETE    VARCHAR2(100)  default 'n'    NULL,
    TIPBOARD_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_tipboardno;
create sequence seq_tipboardno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  TIPBOARD_REPLY  (
    TIPREPLY_NO    NUMBER      NOT NULL,
    TIPREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    TIPREPLY_DATE    DATE  default sysdate    NOT NULL,
    TIP_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    TIPREPLY_DELETE    VARCHAR2(100)  default 'n'    NULL
);
drop sequence seq_tipreplyno;
create sequence seq_tipreplyno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  FREEBOARD  (
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_TITLE    VARCHAR2(100)      NOT NULL,
    FREEBOARD_CONTENT    VARCHAR2(4000)      NOT NULL,
    FREEBOARD_DATE    DATE  default sysdate    NOT NULL,
    FREEBOARD_ORIGINFILE    VARCHAR2(100)      NULL,
    FREEBOARD_VIEWS    NUMBER      NOT NULL,
    FREEBOARD_RECOMMEND    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)   default 'n'   NULL,
    FREEBOARD_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_freeboardno;
create sequence seq_freeboardno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  FREEBOARD_REPLY  (
    FREEREPLY_NO    NUMBER      NOT NULL,
    FREEREPLY_CONTENT    VARCHAR2(600)      NOT NULL,
    FREEREPLY_DATE    DATE  default sysdate    NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    FREEBOARD_NO    NUMBER      NOT NULL,
    FREEBOARD_DELETE    VARCHAR2(100)  default 'n'    NULL
);

drop sequence seq_freereplyno;
create sequence seq_freereplyno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  MANAGER  (
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    MANAGER_NAME    VARCHAR2(100)      NOT NULL,
    MANAGER_PASSWORD VARCHAR2(100) NOT NULL
);

CREATE TABLE  FAQ  (
    FAQ_NO    NUMBER      NOT NULL,
    FAQ_TITLE    VARCHAR2(100)      NOT NULL,
    FAQ_CONTENT    VARCHAR2(4000)      NOT NULL,
    FAQ_DATE    DATE  default sysdate    NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    FAQ_TYPE VARCHAR2(100) NOT NULL
);

drop sequence seq_faqno;
create sequence seq_faqno
start with 1
increment by 1
nocycle
nocache;

drop sequence seq_prebookingno;
create sequence seq_prebookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  REPORT  (
    REPORT_NO    NUMBER      NOT NULL,
    REPORT_CONTENT    VARCHAR2(4000)      NOT NULL,
    REPORT_CATEGORY    VARCHAR2(100)      NULL,
    BOARD_NO    NUMBER      NULL,
    USER_ID    VARCHAR2(100)      NOT NULL
);

drop sequence seq_reportno;
create sequence seq_reportno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  NOTICE  (
    NOTICE_NO    NUMBER      NOT NULL,
    NOTICE_TITLE    VARCHAR2(100)      NOT NULL,
    NOTICE_CONTENT    VARCHAR2(4000)      NOT NULL,
    NOTICE_DATE    DATE   default sysdate   NOT NULL,
    NOTICE_ORIGINFILE    VARCHAR2(100)      NULL,
    NOTICE_VIEWS    NUMBER      NOT NULL,
    MANAGER_ID    VARCHAR2(100)      NOT NULL,
    NOTICE_DELETE    VARCHAR2(100)   default 'n'   NOT NULL,
    NOTICE_REFILE    VARCHAR2(100)      NULL
);

drop sequence seq_noticeno;
create sequence seq_noticeno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  BOOKING  (
    BOOKING_NO    NUMBER      NOT NULL,
    CHECKIN_DATE    DATE      NOT NULL,
    CHECKOUT_DATE    DATE      NOT NULL,
    PET_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_PROGRESS    VARCHAR2(100)      NOT NULL,
    BOOKING_ETC    VARCHAR2(100)      NULL,
    SERVICE_KIND    VARCHAR2(100)      NOT NULL,
    PUSER_ID	VARCHAR2(100)	NOT NULL,
    PRICE NUMBER NOT NULL
);

drop sequence seq_bookingno;
create sequence seq_bookingno
start with 1
increment by 1
nocycle
nocache;

CREATE TABLE  REVIEW  (
    REVIEW_NO    NUMBER      NOT NULL,
    USER_ID    VARCHAR2(100)      NOT NULL,
    BOOKING_NO    NUMBER      NOT NULL,
    POINT    VARCHAR2(100)      NOT NULL,
    REVIEW_CONTENT    VARCHAR2(600)      NOT NULL,
    REVIEW_ORIGINFILE    VARCHAR2(100)      NULL,
    REVIEW_REFILE    VARCHAR2(100)      NULL,
    REVIEW_DATE  DATE  default sysdate    NOT NULL
);
CREATE TABLE countvisitor (
visit_date DATE NOT NULL,
count_visitor NUMBER DEFAULT 0
);

drop sequence seq_reviewno;
create sequence seq_reviewno
start with 1
increment by 1
nocycle
nocache;

ALTER TABLE  EDU  ADD CONSTRAINT  PK_EDU  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  PK_PET  PRIMARY KEY (
    PET_NO 
);

ALTER TABLE  MEMBER  ADD CONSTRAINT  PK_MEMBER  PRIMARY KEY (
    USER_ID 
);

ALTER TABLE SITTERIMG ADD CONSTRAINT PK_SITTERIMG PRIMARY KEY (
	IMG_NO
);



ALTER TABLE  MESSAGE  ADD CONSTRAINT  PK_MESSAGE  PRIMARY KEY (
    SENDER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  PK_PAYMENT  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  PK_PREBOOKING  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  PK_PREANSWER  PRIMARY KEY (
    PREBOOKING_NO 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  PK_QUESTION  PRIMARY KEY (
    QUESTION_NO 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  PK_ANSWER  PRIMARY KEY (
    QUESTION_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  PK_TIPBOARD  PRIMARY KEY (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  PK_TIPBOARD_REPLY  PRIMARY KEY (
    TIPREPLY_NO 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  PK_FREEBOARD  PRIMARY KEY (
    FREEBOARD_NO 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  PK_FREEBOARD_REPLY  PRIMARY KEY (
    FREEREPLY_NO 
);

ALTER TABLE  MANAGER  ADD CONSTRAINT  PK_MANAGER  PRIMARY KEY (
    MANAGER_ID 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  PK_FAQ  PRIMARY KEY (
    FAQ_NO 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  PK_REPORT  PRIMARY KEY (
    REPORT_NO 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  PK_NOTICE  PRIMARY KEY (
    NOTICE_NO 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  PK_BOOKING  PRIMARY KEY (
    BOOKING_NO 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  PK_REVIEW  PRIMARY KEY (
    REVIEW_NO 
);

ALTER TABLE  EDU  ADD CONSTRAINT  FK_MEMBER_TO_EDU_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PET  ADD CONSTRAINT  FK_MEMBER_TO_PET_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE SITTERIMG ADD CONSTRAINT FK_MEMBER_TO_SITTERIMG_1 FOREIGN KEY (
	USER_ID
)
REFERENCES MEMBER (
	USER_ID
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_1  FOREIGN KEY (
    SENDER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  MESSAGE  ADD CONSTRAINT  FK_MEMBER_TO_MESSAGE_2  FOREIGN KEY (
    REICEIVER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  FK_BOOKING_TO_PAYMENT_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
)  ON DELETE CASCADE;

ALTER TABLE  PREBOOKING  ADD CONSTRAINT  FK_MEMBER_TO_PREBOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_PREBOOKING_TO_PREANSWER_1  FOREIGN KEY (
    PREBOOKING_NO 
)
REFERENCES  PREBOOKING  (
    PREBOOKING_NO 
);

ALTER TABLE  PREANSWER  ADD CONSTRAINT  FK_MEMBER_TO_PREANSWER_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  QUESTION  ADD CONSTRAINT  FK_MEMBER_TO_QUESTION_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  ANSWER  ADD CONSTRAINT  FK_QUESTION_TO_ANSWER_1  FOREIGN KEY (
    QUESTION_NO 
)
REFERENCES  QUESTION  (
    QUESTION_NO 
);

ALTER TABLE  TIPBOARD  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_TIPBOARD_REPLY_1  FOREIGN KEY (
    TIP_NO 
)
REFERENCES  TIPBOARD  (
    TIPBOARD_NO 
);

ALTER TABLE  TIPBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_TIPBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_MEMBER_TO_FREEBOARD_REPLY_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  FREEBOARD_REPLY  ADD CONSTRAINT  FK_FREEBOARD_REPLY_1  FOREIGN KEY (
    FREEBOARD_NO 
)
REFERENCES  FREEBOARD  (
    FREEBOARD_NO 
);

ALTER TABLE  FAQ  ADD CONSTRAINT  FK_MANAGER_TO_FAQ_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  REPORT  ADD CONSTRAINT  FK_MEMBER_TO_REPORT_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  NOTICE  ADD CONSTRAINT  FK_MANAGER_TO_NOTICE_1  FOREIGN KEY (
    MANAGER_ID 
)
REFERENCES  MANAGER  (
    MANAGER_ID 
);

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_PET_TO_BOOKING_1  FOREIGN KEY (
    PET_NO 
)
REFERENCES  PET  (
    PET_NO 
) ON DELETE CASCADE;

ALTER TABLE  BOOKING  ADD CONSTRAINT  FK_MEMBER_TO_BOOKING_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
) ON DELETE CASCADE;

ALTER TABLE BOOKING ADD CONSTRAINT FK_MEMBER_TO_BOOKING_2 FOREIGN KEY (
	PUSER_ID
)
REFERENCES MEMBER (
	USER_ID
) on delete cascade;

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_MEMBER_TO_REVIEW_1  FOREIGN KEY (
    USER_ID 
)
REFERENCES  MEMBER  (
    USER_ID 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_BOOKING_TO_REVIEW_1  FOREIGN KEY (
    BOOKING_NO 
)
REFERENCES  BOOKING  (
    BOOKING_NO 
);
COMMENT ON COLUMN ANSWER.QUESTION_NO IS '질문 번호';
COMMENT ON COLUMN ANSWER.REPLY_CONTENT IS '답변 내용';
COMMENT ON COLUMN ANSWER.REPLY_DATE IS '답변 날짜';

COMMENT ON COLUMN BOOKING.BOOKING_NO IS '예약 번호';
COMMENT ON COLUMN BOOKING.CHECKIN_DATE IS '체크인 날짜';
COMMENT ON COLUMN BOOKING.CHECKOUT_DATE IS '체크아웃 날짜';
COMMENT ON COLUMN BOOKING.PET_NO IS '펫번호';
COMMENT ON COLUMN BOOKING.USER_ID IS '예약자 아이디';
COMMENT ON COLUMN BOOKING.BOOKING_PROGRESS IS '0: 예약신청/ 1: 예약완료/ 2: 결제대기/ 3: 결제완료';
COMMENT ON COLUMN BOOKING.BOOKING_ETC IS '특이사항';
COMMENT ON COLUMN BOOKING.SERVICE_KIND IS '서비스종류';
COMMENT ON COLUMN BOOKING.PUSER_ID IS '펫시터 아이디';

COMMENT ON COLUMN EDU.USER_ID IS '아이디';
COMMENT ON COLUMN EDU.EDU_YN IS '교육 수료 여부(Y/N)';
COMMENT ON COLUMN EDU.SITTER_YN IS '펫시터 여부(Y/N)';

COMMENT ON COLUMN FAQ.FAQ_NO IS '글 번호';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '글 제목';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '글 내용';
COMMENT ON COLUMN FAQ.FAQ_DATE IS '게시 날짜';
COMMENT ON COLUMN FAQ.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN FAQ.FAQ_TYPE IS '종류';

COMMENT ON COLUMN FREEBOARD.FREEBOARD_NO IS '글 번호';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_TITLE IS '글 제목';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_CONTENT IS '글 내용';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_DATE IS '게시 날짜';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_VIEWS IS '조회수';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_RECOMMEND IS '추천수';
COMMENT ON COLUMN FREEBOARD.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_DELETE IS '삭제여부 (Y/N)';
COMMENT ON COLUMN FREEBOARD.FREEBOARD_REFILE IS '수정 파일명';

COMMENT ON COLUMN FREEBOARD_REPLY.FREEREPLY_NO IS '댓글 번호';
COMMENT ON COLUMN FREEBOARD_REPLY.FREEREPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN FREEBOARD_REPLY.FREEREPLY_DATE IS '댓글 게시일자';
COMMENT ON COLUMN FREEBOARD_REPLY.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN FREEBOARD_REPLY.FREEBOARD_NO IS '원글 번호';
COMMENT ON COLUMN FREEBOARD_REPLY.FREEBOARD_DELETE IS '삭제여부 (Y/N)';

COMMENT ON COLUMN MANAGER.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN MANAGER.MANAGER_NAME IS '관리자명';
COMMENT ON COLUMN MANAGER.MANAGER_PASSWORD IS '비밀번호';

COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.JOB IS '직업';
COMMENT ON COLUMN MEMBER.PETSITTER IS '펫시터회원 여부 0: 일반/ 1: 승인대기중/ 2: 펫시터';
COMMENT ON COLUMN MEMBER.PRICE IS '가격(일)';
COMMENT ON COLUMN MEMBER.USER_DATE IS '생년월일';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_DELETE IS '삭제여부(Y/N)';
COMMENT ON COLUMN MEMBER.USER_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN MEMBER.USER_REFILE IS '수정 파일명';

COMMENT ON COLUMN MESSAGE.SENDER_ID IS '보낸사람 아이디';
COMMENT ON COLUMN MESSAGE.MESSAGE_TITLE IS '쪽지 제목';
COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENT IS '쪽지 내용';
COMMENT ON COLUMN MESSAGE.MESSAGE_READ IS '읽음 여부';
COMMENT ON COLUMN MESSAGE.MESSAGE_DATE IS '보낸 날짜';
COMMENT ON COLUMN MESSAGE.REICEIVER_ID IS '받는 사람 아이디';

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '글 번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '글 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '글 내용';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '게시 일자';
COMMENT ON COLUMN NOTICE.NOTICE_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN NOTICE.NOTICE_VIEWS IS '조회수';
COMMENT ON COLUMN NOTICE.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN NOTICE.NOTICE_DELETE IS '삭제여부';
COMMENT ON COLUMN NOTICE.NOTICE_REFILE IS '수정 파일명';

COMMENT ON COLUMN PAYMENT.BOOKING_NO IS '예약 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제 날짜';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '결제 방식';
COMMENT ON COLUMN PAYMENT.PAYMENT_YN IS '결제 여부';

COMMENT ON COLUMN PET.PET_NO IS '강아지 번호';
COMMENT ON COLUMN PET.PET_NAME IS '이름';
COMMENT ON COLUMN PET.PET_BREADS IS '견종';
COMMENT ON COLUMN PET.PET_DATE IS '생년월일';
COMMENT ON COLUMN PET.PET_SIZE IS '크기';
COMMENT ON COLUMN PET.PET_GENDER IS '성별(M/F)';
COMMENT ON COLUMN PET.PET_NEUTRALIZE IS '중성화 여부';
COMMENT ON COLUMN PET.PET_CHARATER IS '특징';
COMMENT ON COLUMN PET.USER_ID IS '주인 아이디';
COMMENT ON COLUMN PET.PET_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN PET.PET_REFILE IS '수정 파일명';

COMMENT ON COLUMN PREANSWER.PREBOOKONG_NO IS '사전문의번호';
COMMENT ON COLUMN PREANSWER.USER_ID IS '아이디';
COMMENT ON COLUMN PREANSWER.ANSWER_CONTENT IS '답변 내용';
COMMENT ON COLUMN PREANSWER.ANSWER_DATE IS '답변 일자';

COMMENT ON COLUMN PREBOOKING.PREBOOKING_NO IS '사전문의번호';
COMMENT ON COLUMN PREBOOKING.USER_ID IS '아이디';
COMMENT ON COLUMN PREBOOKING.PREBOOKING_TITLE IS '제목';
COMMENT ON COLUMN PREBOOKING.PREBOOKING_CONTENT IS '내용';
COMMENT ON COLUMN PREBOOKING.PREBOOKING_DATE IS '게시일';
COMMENT ON COLUMN PREBOOKING.ANSWER_YN IS '답변 여부(Y/N)';

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '글 번호';
COMMENT ON COLUMN QUESTION.QUESTION_TITLE IS '제목';
COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '내용';
COMMENT ON COLUMN QUESTION.QUESTION_DATE IS '게시일자';
COMMENT ON COLUMN QUESTION.REPLY_YN IS '답변여부';
COMMENT ON COLUMN QUESTION.USER_ID IS '아이디';

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고 번호';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고 내용';
COMMENT ON COLUMN REPORT.REPORT_CATEGORY IS '신고 종류';
COMMENT ON COLUMN REPORT.BOARD_NO IS '글 번호';
COMMENT ON COLUMN REPORT.USER_ID IS '아이디';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰 번호';
COMMENT ON COLUMN REVIEW.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN REVIEW.BOOKING_NO IS '예약 번호';
COMMENT ON COLUMN REVIEW.POINT IS '평점';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '내용';
COMMENT ON COLUMN REVIEW.REVIEW_ORGINFILE IS '원본 파일명';
COMMENT ON COLUMN REVIEW.REVIEW_REFILE IS '수정 파일명';

COMMENT ON COLUMN SITTERIMG.IMG_NO IS '이미지 번호';
COMMENT ON COLUMN SITTERIMG.USER_ID IS '아이디';
COMMENT ON COLUMN SITTERIMG.IMG_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN SITTERIMG.IMG_REFILE IS '수정파일명';

COMMENT ON COLUMN TIPBOARD.TIPBOARD_NO IS '글 번호';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_TITLE IS '글 제목';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_CONTENT IS '글 내용';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_DATE IS '게시일자';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_ORIGINFILE IS '원본 파일명';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_VIEWS IS '조회수';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_RECOMMEND IS '추천수';
COMMENT ON COLUMN TIPBOARD.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_DELETE IS '삭제여부(Y/N)';
COMMENT ON COLUMN TIPBOARD.TIPBOARD_REFILE IS '수정 파일명';

COMMENT ON COLUMN TIPBOARD_REPLY.TIPREPLY_NO IS '댓글 번호';
COMMENT ON COLUMN TIPBOARD_REPLY.TIPREPLY_CONTENT IS '내용';
COMMENT ON COLUMN TIPBOARD_REPLY.TIPREPLY_DATE IS '게시일자';
COMMENT ON COLUMN TIPBOARD_REPLY.TIP_NO IS '원글 번호';
COMMENT ON COLUMN TIPBOARD_REPLY.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN TIPBOARD_REPLY.TIPREPLY_DELETE IS '삭제 여부(Y/N)';

COMMENT ON COLUMN COUNTVISITOR.VISIT_DATE IS '회원 방문 날짜';
COMMENT ON COLUMN COUNTVISITOR.COUNT_VISITOR IS '방문한 회원 수';



insert into manager values('manager','매니저이름1','pass01');
insert into notice values(seq_noticeno.nextval,'1번글','1번내용',default,'0',0,'manager','n','0');

INSERT INTO MEMBER VALUES ( 'tjrghekt', 'tjrghekt@naver.com', '홍길동', ' 서울시 광진구 강변북로 36, (뚝섬유란선 선착장)', '011-1234-1234', '학생', '2', 5000, sysdate, 1234,'N',NULL,NULL,NULL,NULL,NULL,NULL );
INSERT INTO MEMBER VALUES ('admin', 'admin@gmail.com','김석호','서울시 강남구 개포로22길 34','010-5345-2344','학생','2',10000,  sysdate, '1234','N',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO MEMBER VALUES ('user01', 'user01@naver.com','김유저','경기도 화성시 팔탄면 가재울길 3','010-1234-5435','주부','2',20000,  sysdate, '1234','N',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO MEMBER VALUES ('user02','user2@naver.com','오길동','경기도 화성시 팔탄면 가재울길 3','010-1111-1111','직장인',default,0,'91/06/18','pass01',default,null,null,null,null,default,null);
INSERT INTO MEMBER VALUES ( 'user03', 'user03@naver.com', '박형제', ' 서울시 성동구 강변북로 257, (뚝섬유란선 선착장)', '011-4234-1234', '직장인', '2', 40000, sysdate, 1234,'N',NULL,NULL,NULL ,NULL,NULL,NULL);

insert into member values('je615','lolje615@gmail.com','장금이','평택','010-0032-3200','궁녀',default,0,'92/06/16','je01',default,null,null,null,NULL,default,null);
insert into member values ('admin', 1,1,1,1,1,0,10000,  sysdate, '1234','n',null,null,NULL,null,default,null);

insert into tipboard values(seq_tipboardno.nextval,'팁1번글','1번글 내용',default,null,0,0,'user01',default,null );
insert into tipboard values(seq_tipboardno.nextval,'팁2번글','2번글 내용',default,null,0,0,'user01',default,null );


insert into pet values(seq_petno.nextval, '1번펫', '1',sysdate, '대형','수컷','n','사나움','user02',null,null);


insert into faq values(seq_faqno.nextval, 'faqtest', '내용', sysdate, 'manager', '기타');
commit;


INSERT INTO PET VALUES(SEQ_PETNO.NEXTVAL, '달리', '치와와', '2010/01/01', '중형', 'M', 'N', NULL, 'admin', NULL, NULL );
INSERT INTO PET VALUES(SEQ_PETNO.NEXTVAL, '초코', '말티즈', '2018/04/08', '소형', 'M', 'Y', NULL, 'tjrghekt', NULL, NULL);
alter session set nls_date_format = 'RRRR/MM/DD hh24:MI'; 
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/01 15:00', '2019/01/03 17:00', 1, 'admin', 1, '잘부탁드립니다',  2, 'tjrghekt', 15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/03 12:10', '2019/01/06 17:00', 1, 'admin', 3, '애기 잘 봐주세요',  2, 'tjrghekt',20000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/20 15:00', '2019/01/22 15:00', 1, 'admin', 3, '안녕하세요~',  1, 'tjrghekt',15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/02/01 15:00', '2019/02/01 17:00', 1, 'admin', 3, '또 와썽요!!',  2, 'tjrghekt', 4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/01 12:10', '2019/03/01 15:00', 1, 'admin', 1, 'ㅎㅇㅎㅇ',  0, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/01 11:00', '2019/01/03 15:00', 2, 'user01', 1, '잘부탁드립니다',  1, 'tjrghekt',15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/03 11:00', '2019/01/06 17:00', 2, 'user01', 2, '애기 잘 봐주세요',  3, 'tjrghekt',20000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/01/20 12:10', '2019/01/22 15:00', 2, 'user01', 2, '안녕하세요~',  1, 'tjrghekt',15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/02/01 11:00', '2019/02/01 17:00', 2, 'user01', 3, '또 와썽요!!',  2, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/01 15:00', '2019/03/01 17:00', 2, 'user01', 1, 'ㅎㅇㅎㅇ',  2, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/01 12:10', '2019/03/01 15:00', 2, 'tjrghekt', 2, 'ㅎㅇㅎㅇ',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/07 11:00', '2019/03/07 17:00', 2, 'tjrghekt', 3, '내용 없음',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/01 11:00', '2019/03/02 16:00', 2, 'tjrghekt', 2, '잘봐주세요!',  1, 'admin',5000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/08 12:10', '2019/03/08 16:00', 3, 'user03', 1, '잘봐주세요!',  0, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/20 14:00', '2019/04/20 16:00', 2, 'user01', 1, '날씨가 좋네요 고생하세요!',  0, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/01 15:00', '2019/04/03 16:00', 2, 'user01', 1, '잘부탁드립니다',  1, 'tjrghekt',15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/01 12:10', '2019/04/01 15:00', 1, 'admin', 1, '힘드실텐데 고생하십쇼!',  0, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/09 12:10', '2019/03/09 16:00', 3, 'user03', 1, '잘봐주세요!',  0, 'tjrghekt',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/21 14:00', '2019/04/21 16:00', 2, 'user01', 1, '애가 밥을 잘먹어요 밥 많이주세요!!!',  0, 'tjrghekt', 4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/03 12:10', '2019/04/05 15:00', 2, 'user01', 1, '잘부탁드립니다',  1, 'tjrghekt', 15000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/04 12:10', '2019/04/04 16:10', 1, 'admin', 1, '산책 꼭 시켜주세요!',  0, 'tjrghekt', 4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/03 12:10', '2019/03/03 15:00', 2, 'tjrghekt', 2, '언제나 감사해요~',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/09 11:00', '2019/03/09 17:00', 2, 'tjrghekt', 3, '이번에도 잘부탁드립니다요',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/03/30 11:00', '2019/03/31 16:00', 2, 'tjrghekt', 2, '잘봐주세요!',  1, 'admin',5000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/01 12:10', '2019/04/01 15:00', 2, 'tjrghekt', 2, 'ㅎㅇㅎㅇ',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/07 11:00', '2019/04/07 17:00', 2, 'tjrghekt', 3, '항상 감사합니다',  0, 'admin',4000);
INSERT INTO BOOKING VALUES(SEQ_BOOKINGNO.NEXTVAL, '2019/04/15 11:00', '2019/04/16 16:00', 2, 'tjrghekt', 2, '잘봐주세요!',  1, 'admin',5000);

insert into freeboard values (SEQ_FREEBOARDNO.nextval, '목줄 몸통 감싸는거 하니까 좋네요', '좀 더 편안해하는거 같아요', '2019-03-27', null, 0, 0, 'user01', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '꽃구경 다들 어디로 가세여?', '장소추천좀', '2019-03-31', null, 0, 0, 'tjrghekt', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '오늘 호야랑 산책다녀왔는데', '추워서 죽는줄 알았어요', '2019-04-02', null, 0, 0, 'user01', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '강아지 사료 추천받아요', '맛있는거 뭐 없을까요', '2019-03-31', null, 0, 0, 'user01', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '평택에 동물병원 괜찮은 곳 없나요?', '이사온 지 얼마 안됐는데 어디로 가야할지 모르겠네요', '2019-03-15', null, 0, 0, 'user02', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '목줄 말인데요', '목에 끼는거 쓰시나요 몸통끼는거 쓰시나요?', '2019-03-18', null, 0, 0, 'tjrghekt', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '겨울엔 산책가기 힘든거 같아요', '돌이는 좋다고 난리지만 나는 너무 추운것..', '2019-02-10', null, 0, 0, 'je615', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '이번에 서비스 처음 이용해봤는데', '나름 괜찮은 것 같아요. 자세한건 좀 더 이용해봐야할듯 다들 어떠셨음?', '2019-03-01', null, 0, 0, 'je615', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '사료 추천받습니다', '이번에 사료 바꿔주려고 하는데 뭐가 좋나요?', '2019-03-18', null, 0, 0, 'user02', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '서울 공기 너무 안좋네요', '강아지랑 산책나왔는데 거의 안개수준이네요', '2019-03-18', null, 0, 0, 'tjrghekt', 'n',null);
insert into freeboard values (SEQ_FREEBOARDNO.nextval, '일교차가 너무 심한데', '감기조심하세요', '2019-04-01', null, 0, 0, 'je615', 'n',null);
commit;


insert into review values(seq_reviewno.nextval, (select user_id from booking where booking_no = 6), 6, 3, '석호닷님 이번에도 감사합니다', null, null, default);
UPDATE BOOKING SET BOOKING_PROGRESS = '4' WHERE BOOKING_NO = 6;
commit;

