--1번
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

--2번
SELECT department_name || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

--3번
SELECT STUDENT_NAME 
FROM tb_student s, TB_DEPARTMENT d
WHERE s.department_no = d.department_no and department_name = '국어국문학과' 
    and ABSENCE_YN = 'Y' and STUDENT_SSN LIKE '_______2%';
    
--4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513%' AND STUDENT_NO > 'A513078';

--5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

--6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9번
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE entrance_date LIKE '02%' AND STUDENT_ADDRESS LIKE '전주%' AND ABSENCE_YN = 'N';

