package board.model.vo;

public class Board {

	public Board() {}
	
	
	FREEBOARD_NO	NUMBER
	FREEBOARD_TITLE	VARCHAR2(100 BYTE)
	FREEBOARD_CONTENT	VARCHAR2(100 BYTE)
	FREEBOARD_DATE	DATE
	FREEBOARD_FILE	VARCHAR2(100 BYTE)
	FREEBOARD_VIEWS	NUMBER
	FREEBOARD_RECOMMEND	NUMBER
	USER_ID	VARCHAR2(100 BYTE)
	FREEBOARD_DELETE_YN	VARCHAR2(255 BYTE)
}
