/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-19 09:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/..//views/common/footer.jsp", Long.valueOf(1552978184648L));
    _jspx_dependants.put("/..//views/common/menu.jsp", Long.valueOf(1552988815808L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Dog House</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<!-- 변경확인용 주석2  -->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<link href=\"/doggybeta/resources/css/footer.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<style>\n");
      out.write(".mySlides {\n");
      out.write("\tdisplay: none\n");
      out.write("}\n");
      out.write("\n");
      out.write(".w3-left, .w3-right, .w3-badge {\n");
      out.write("\tcursor: pointer\n");
      out.write("}\n");
      out.write(".w3-badge {\n");
      out.write("\theight: 13px;\n");
      out.write("\twidth: 13px;\n");
      out.write("\tpadding: 0\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src='/doggybeta/resources/js/loginSource.js'></script> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/doggybeta/resources/css/psForm.css\">\r\n");
      out.write("<link href='/doggybeta/resources/css/login.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/doggybeta/resources/css/mainV2.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t $(function() {\r\n");
      out.write(" \t\t$('.login-form').hide();\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t$('.btn').click(function() {\r\n");
      out.write("\t\t\t$('body').append('<div id=\"mask\"></div>');\r\n");
      out.write("\t\t    $('#mask').fadeIn(300);\r\n");
      out.write("\t\t    $('.login-form').fadeIn(300);\r\n");
      out.write("\t\t\t$('.login-form').show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    $('#mask').click(function() {\r\n");
      out.write("\t\t    \t$('#mask, .login-form').fadeOut(300);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btnLogin').click(function(){\r\n");
      out.write("\t\t\tvar userid = $('#userid').val();\r\n");
      out.write("\t\t\tvar passwd = $('#passwd').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(userid == \"\") {\r\n");
      out.write("\t\t\t\t$('#userid').focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/* var exp = '/[a-z0-9]$/';\r\n");
      out.write("\t\t\tif(!exp.test(userid)) {\r\n");
      out.write("\t\t\t\t$('#userid').focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(passwd == \"\") {\r\n");
      out.write("\t\t\t\t$('#passwd').focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar data = \"userid=\"+userid+\"&passwd=\"+passwd;\r\n");
      out.write("\t\t\talert(userid+passwd);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: 'post',\r\n");
      out.write("\t\t\t\tdata: {userid : $('#userid').val(), passwd : $('#passwd').val() },\r\n");
      out.write("\t\t\t\turl: '/doggybeta/jipsalogin',\r\n");
      out.write("\t\t\t\tsuccess: function(value) {\r\n");
      out.write("\t\t\t\t\talert('사용할 수 있는 아이디입니다.');\r\n");
      out.write("\t\t\t\t}//success\r\n");
      out.write("\t\t\t});//ajax\r\n");
      out.write("\t\t})//login btn\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("\t<input type='checkbox' id='menu_state' checked />\r\n");
      out.write("\t<div id='mask'> </div>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul class='doghouse'>\r\n");
      out.write("\t\t\t<li><a><span>doghouse</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<span class='btn btn-1 btn-sign'>회원가입/로그인</span>\r\n");
      out.write("\t\t<!-- ---------------------------------------------------------------------------- -->\r\n");
      out.write("<!-- \t\t<a href=\"#\" class=\"login-forgot-pass\">forgot password?</a>\r\n");
      out.write("\t\t<div class=\"underlay-photo\"></div>\r\n");
      out.write("\t\t<div class=\"underlay-black\"></div>  -->\r\n");
      out.write("\t\t<!-- -------------------------------------------------------------------------  -->\r\n");
      out.write("\t\t<ul class='icon' id='icon'>\r\n");
      out.write("\t\t\t<!-- <li><img id='logo' src='/doggybeta/resources/images/doglogo.png'\r\n");
      out.write("\t\t\t\twidth='80%' /><a><span>doghouse</span> </a></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href='/doggybeta' id='icon1'> <span>&nbsp;&nbsp;&nbsp;홈</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a\r\n");
      out.write("\t\t\t\thref=\"/doggybeta/views/aboutus/companyintroduce.jsp\" id='icon2'><span>&nbsp;&nbsp;&nbsp;About\r\n");
      out.write("\t\t\t\t\t\tus</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/companyIntroduce.jsp\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>연혁</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/teamIntroduce.jsp\">팀\r\n");
      out.write("\t\t\t\t\t\t\t도그집사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/location.jsp\">오시는 길</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href='#' id='icon3'> <span>&nbsp;&nbsp;&nbsp;펫시터\t찾기</span></a> </li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href='#'  id='icon4'> <span>&nbsp;&nbsp;&nbsp;게시판</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/nlist'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/tlist'>팁</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"/doggybeta/faqlist\" id='icon5'> <span>&nbsp;&nbsp;&nbsp;고객센터</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/faqlist'>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용방법</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon6'><span>&nbsp;&nbsp;&nbsp;마이페이지</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용내역/예약확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#' id=\"pet_reg__btn\">펫시터신청</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>사전문의확인</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- ------------------------------------------------- -->\r\n");
      out.write("\t<form class=\"login-form\" method='post' action='/doggybeta/jipsalogin'>\r\n");
      out.write("  \t\t\t<p class=\"login-text\">\r\n");
      out.write("    \t\t\t<span class=\"fa-stack fa-lg\">\r\n");
      out.write("      \t\t\t\t<i class=\"fa fa-circle fa-stack-2x\"></i>\r\n");
      out.write("      \t\t\t\t<i class=\"fa fa-lock fa-stack-1x\"></i>\r\n");
      out.write("    \t\t\t</span>\r\n");
      out.write("  \t\t\t</p>\r\n");
      out.write("  \t\t\t<input type=\"text\" name='userid' id='userid' class=\"login-username\" autofocus required placeholder=\"Email\" />\r\n");
      out.write("  \t\t\t<input type=\"password\" name='userpwd' id='passwd' class=\"login-password\" required required placeholder=\"Password\" />\r\n");
      out.write("  \t\t\t<a href='/doggybeta/jipsalogin'>\r\n");
      out.write("  \t\t\t<input type=\"submit\" name=\"Login\" value=\"Login\" class=\"login-submit\" id='btnLogin'/></a>\r\n");
      out.write("\t\t\t<a href='/doggybeta/views/member/enroll.html'>\r\n");
      out.write("\t\t\t<input type=\"button\" name='enroll' value='회원가입' class='login-submit' id='btnEnroll'/>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t&nbsp;\r\n");
      out.write("  \t\t\t<a href=\"/doggybeta/views/member/findPassword.jsp\" class=\"login-forgot-pass\" id='tempPwd'>forgot password?</a>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('.m1').hover(function() {\r\n");
      out.write("\t\tif ($(this).children('.m2').is(':visible')) {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideUp(800);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideDown(800);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<input type='checkbox' id='menu_state' checked />\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul class='doghouse'>\r\n");
      out.write("\t\t\t<li><a><span>doghouse</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a  href='/doggybeta/jipsalogout'><span class='btn btn-1 btn-sign'>로그아웃</span></a>\r\n");
      out.write("\t\t");
      out.print( loginUser.getUserId() );
      out.write("\r\n");
      out.write("\t\t<!-- ---------------------------------------------------------------------------- -->\r\n");
      out.write("<!-- \t\t<a href=\"#\" class=\"login-forgot-pass\">forgot password?</a>\r\n");
      out.write("\t\t<div class=\"underlay-photo\"></div>\r\n");
      out.write("\t\t<div class=\"underlay-black\"></div>  -->\r\n");
      out.write("\t\t<!-- -------------------------------------------------------------------------  -->\r\n");
      out.write("\t\t<ul class='icon' id='icon'>\r\n");
      out.write("\t\t\t<li><a href='/doggybeta' id='icon1'> <span>&nbsp;&nbsp;&nbsp;홈</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a\r\n");
      out.write("\t\t\t\thref=\"/doggybeta/views/aboutus/companyintroduce.jsp\" id='icon2'><span>&nbsp;&nbsp;&nbsp;About\r\n");
      out.write("\t\t\t\t\t\tus</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/companyIntroduce.jsp\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>연혁</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/teamIntroduce.jsp\">팀\r\n");
      out.write("\t\t\t\t\t\t\t도그집사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/location.jsp\">오시는 길</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href='#' id='icon3'> <span>&nbsp;&nbsp;&nbsp;펫시터\t찾기</span></a> </li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href='#'  id='icon4'> <span>&nbsp;&nbsp;&nbsp;게시판</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>팁</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon5'> <span>&nbsp;&nbsp;&nbsp;고객센터</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용방법</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon6'><span>&nbsp;&nbsp;&nbsp;마이페이지</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용내역/예약확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#' id=\"pet_reg__btn\">펫시터신청</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>사전문의확인</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 펫시터 신청 버튼 클릭시 생성 보여지는 HTML 부분. 로그인 부분 구현시 인풋에 세션으로 값 넣어놓고 readonly 처리할 것  -->\r\n");
      out.write("\t\t<div class=\"ps_reg_form\" >\r\n");
      out.write("\t\t\t<span class=\"close\">x</span>\r\n");
      out.write("\t\t\t\t<div class=\"section1\">\r\n");
      out.write("\t\t\t\t\t<p>아이디</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"userid\" placeholder=\"");
      out.print(loginUser.getUserId() );
      out.write("\"  class=\"ps_input input_id\" autocomplete=\"off\" readonly>\r\n");
      out.write("\t\t\t\t\t<p>이름</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"username\" placeholder=\"이름 입력\"  class=\"ps_input input_name\" autocomplete=\"off\" readonly>\r\n");
      out.write("\t\t\t\t\t<p>회원 약관</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>개인 정보 수집</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>제 3자 개인 정보 제공</p>\r\n");
      out.write("\t\t\t\t\t<button class=\"normal_btn\">내용보기</button>\r\n");
      out.write("\t\t\t\t\t<p>전체 동의 여부</p>\r\n");
      out.write("\t\t\t\t\t<span><label>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"agree\" value=\"agree\" checked> 동의\r\n");
      out.write("\t\t\t\t\t</label><label>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"agree\" value=\"disagree\"> 동의하지않음\r\n");
      out.write("\t\t\t\t\t</label></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section2\">\r\n");
      out.write("\t\t\t\t\t<p>연락처</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"phone\" placeholder=\"핸드폰 번호 입력\" class=\"ps_input input_phone\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t<p>이메일</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"email\" placeholder=\"이메일 입력\" class=\"ps_input input_email\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t<p>펫시팅 장소</p>\r\n");
      out.write("\t\t\t\t\t<input name=\"addr\" placeholder=\"장소/위치 입력\" class=\"ps_input input_addr\" autocomplete=\"off\" >\r\n");
      out.write("\t\t\t\t\t<p>희망 시급(원)</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" name=\"price\" placeholder=\"가격 입력\" class=\"ps_input input_price\" min=\"100\" step=\"100\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"image_box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"image_box_pic\"></div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" id=\"real-file\" hidden=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"fake-file-btn\" class=\"normal_btn\">Choose a File</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"file-text\"></span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"map_box\"></div>\r\n");
      out.write("\t\t\t\t\t<span><button type=\"submit\" id=\"submit-btn\">펫시터 등록하기</button></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\"src=\"/doggybeta/resources/js/petSitting.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('.m1').hover(function() {\r\n");
      out.write("\t\tif ($(this).children('.m2').is(':visible')) {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideUp(800);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(this).children('.m2').slideDown(800);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- <script src=\"/doggybeta/resources/js/loginSource.js\"></script> -->\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t<div id=\"wrap\">\n");
      out.write("\t\t  <div id=\"content\">\n");
      out.write("\t\t\t<!-- 내용작성  -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"w3-container\"></div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"w3-content w3-display-container\" style=\"max-width: 100%;\">\n");
      out.write("\t\t\t\t<img class=\"mySlides\" src=\"/doggybeta/resources/images/backdog1.jpg\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%;\"> <img class=\"mySlides\"\n");
      out.write("\t\t\t\t\tsrc=\"/doggybeta/resources/images/dog2.jpg\" style=\"width: 100%\">\n");
      out.write("\t\t\t\t<img class=\"mySlides\" src=\"/doggybeta/resources/images/backdog1.jpg\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%\">\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%\">\n");
      out.write("\t\t\t\t\t<div class=\"w3-left w3-hover-text-khaki\" onclick=\"plusDivs(-1)\">\n");
      out.write("\t\t\t\t\t\t<font size=15pt>&#10094;</font>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"w3-right w3-hover-text-khaki\" onclick=\"plusDivs(1)\">&#10095;</div>\n");
      out.write("\t\t\t\t\t<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(1)\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(2)\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(3)\"></span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"footer\">");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("/* footer {\n");
      out.write("\ttext-align:center;\n");
      out.write("    bottom:0;\n");
      out.write("    width:120%;\n");
      out.write("    background:#ccc;\n");
      out.write("    margin-bottom:0;\n");
      out.write("    border-top-width: 0;\n");
      out.write("} */\n");
      out.write("/* footer{\n");
      out.write("\twidth:100%;\n");
      out.write("\theight:60px; \n");
      out.write("\tposition:absolute;\n");
      out.write("\tbottom:0; \n");
      out.write("\tleft:0;\n");
      out.write("\tbackground:#ccc;\n");
      out.write("\ttext-align:center;\n");
      out.write("} */\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("copyright@kh.org 2019-03-04 master : 홍길동 <br>\n");
      out.write("tel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script>\n");
      out.write("\t\tvar slideIndex = 1;\n");
      out.write("\t\tshowDivs(slideIndex);\n");
      out.write("\n");
      out.write("\t\tfunction plusDivs(n) {\n");
      out.write("\t\t\tshowDivs(slideIndex += n);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction currentDiv(n) {\n");
      out.write("\t\t\tshowDivs(slideIndex = n);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction showDivs(n) {\n");
      out.write("\t\t\tvar i;\n");
      out.write("\t\t\tvar x = document.getElementsByClassName(\"mySlides\");\n");
      out.write("\t\t\tvar dots = document.getElementsByClassName(\"demo\");\n");
      out.write("\t\t\tif (n > x.length) {\n");
      out.write("\t\t\t\tslideIndex = 1\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (n < 1) {\n");
      out.write("\t\t\t\tslideIndex = x.length\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfor (i = 0; i < x.length; i++) {\n");
      out.write("\t\t\t\tx[i].style.display = \"none\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfor (i = 0; i < dots.length; i++) {\n");
      out.write("\t\t\t\tdots[i].className = dots[i].className.replace(\" w3-white\", \"\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tx[slideIndex - 1].style.display = \"block\";\n");
      out.write("\t\t\tdots[slideIndex - 1].className += \" w3-white\";\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
