/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-17 07:28:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/..//views/common/footer.jsp", Long.valueOf(1552499463104L));
    _jspx_dependants.put("/..//views/common/menu.jsp", Long.valueOf(1552807677437L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Dog House</title>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link href=\"/doggybeta/resources/css/footer.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write(".mySlides {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".w3-left, .w3-right, .w3-badge {\r\n");
      out.write("\tcursor: pointer\r\n");
      out.write("}\r\n");
      out.write(".w3-badge {\r\n");
      out.write("\theight: 13px;\r\n");
      out.write("\twidth: 13px;\r\n");
      out.write("\tpadding: 0\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/doggybeta/resources/css/mainV2.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/doggybeta/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type='checkbox' id='menu_state' checked />\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul class='doghouse'>\r\n");
      out.write("\t\t\t<li><a><span>doghouse</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<button class='btn btn-1 btn-sign'><a href=\"\">회원가입<br>로그인</a></button>\r\n");
      out.write("\t\t<ul class='icon' id='icon'>\r\n");
      out.write("\t\t\t<!-- <li><img id='logo' src='/doggybeta/resources/images/doglogo.png'\r\n");
      out.write("\t\t\t\twidth='80%' /><a><span>doghouse</span> </a></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href='/doggybeta' id='icon1'> <span>&nbsp;&nbsp;&nbsp;홈</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a\r\n");
      out.write("\t\t\t\thref=\"/doggybeta/views/aboutus/companyIntroduce.jsp\" id='icon2'><span>&nbsp;&nbsp;&nbsp;About\r\n");
      out.write("\t\t\t\t\t\tus</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/companyIntroduce.jsp\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>연혁</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/teamIntroduce.jsp\">팀\r\n");
      out.write("\t\t\t\t\t\t\t도그집사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/doggybeta/views/aboutus/location.jsp\">오시는 길</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href='/doggybeta/views/findSitter/petSitterListView.jsp' id='icon3'> <span>&nbsp;&nbsp;&nbsp;펫시터\t찾기</span></a> </li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href='#'  id='icon4'> <span>&nbsp;&nbsp;&nbsp;게시판</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='/doggybeta/tlist'>팁</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon5'> <span>&nbsp;&nbsp;&nbsp;고객센터</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용방법</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"m1\"><a href=\"#\" id='icon6'><span>&nbsp;&nbsp;&nbsp;마이페이지</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"m2\">\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>이용내역/예약확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>펫시터신청</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='#'>사전문의확인</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$('.m1').hover(function() {\r\n");
      out.write("\t\t\t\tif ($(this).children('.m2').is(':visible')) {\r\n");
      out.write("\t\t\t\t\t$(this).children('.m2').slideUp(800);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(this).children('.m2').slideDown(800);\r\n");
      out.write("\t\t\t\t\t$('.fa').ready(function() {\r\n");
      out.write("\t\t\t\t\t\tevent.stopPropagation()\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t  <div id=\"content\">\r\n");
      out.write("\t\t\t<!-- 내용작성  -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"w3-container\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"w3-content w3-display-container\" style=\"max-width: 100%;\">\r\n");
      out.write("\t\t\t\t<img class=\"mySlides\" src=\"/doggybeta/resources/images/backdog1.jpg\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%;\"> <img class=\"mySlides\"\r\n");
      out.write("\t\t\t\t\tsrc=\"/doggybeta/resources/images/dog2.jpg\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t<img class=\"mySlides\" src=\"/doggybeta/resources/images/backdog1.jpg\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-left w3-hover-text-khaki\" onclick=\"plusDivs(-1)\">\r\n");
      out.write("\t\t\t\t\t\t<font size=15pt>&#10094;</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-right w3-hover-text-khaki\" onclick=\"plusDivs(1)\">&#10095;</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(1)\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(2)\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"w3-badge demo w3-border w3-transparent w3-hover-white\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"currentDiv(3)\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* footer {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("    bottom:0;\r\n");
      out.write("    width:120%;\r\n");
      out.write("    background:#ccc;\r\n");
      out.write("    margin-bottom:0;\r\n");
      out.write("    border-top-width: 0;\r\n");
      out.write("} */\r\n");
      out.write("/* footer{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:60px; \r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tbottom:0; \r\n");
      out.write("\tleft:0;\r\n");
      out.write("\tbackground:#ccc;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("} */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("copyright@kh.org 2019-03-04 master : 홍길동 <br>\r\n");
      out.write("tel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar slideIndex = 1;\r\n");
      out.write("\t\tshowDivs(slideIndex);\r\n");
      out.write("\r\n");
      out.write("\t\tfunction plusDivs(n) {\r\n");
      out.write("\t\t\tshowDivs(slideIndex += n);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction currentDiv(n) {\r\n");
      out.write("\t\t\tshowDivs(slideIndex = n);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showDivs(n) {\r\n");
      out.write("\t\t\tvar i;\r\n");
      out.write("\t\t\tvar x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t\t\tvar dots = document.getElementsByClassName(\"demo\");\r\n");
      out.write("\t\t\tif (n > x.length) {\r\n");
      out.write("\t\t\t\tslideIndex = 1\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (n < 1) {\r\n");
      out.write("\t\t\t\tslideIndex = x.length\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (i = 0; i < x.length; i++) {\r\n");
      out.write("\t\t\t\tx[i].style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t\t\t\tdots[i].className = dots[i].className.replace(\" w3-white\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx[slideIndex - 1].style.display = \"block\";\r\n");
      out.write("\t\t\tdots[slideIndex - 1].className += \" w3-white\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
